version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.12
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16688:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      monitoring:
        aliases:
          - jaeger
  demo-app:
    image: mononoke/demo-app:latest
    ports:
      - 8000:8000
    environment:
            - opentracing.jaeger.udp-sender.host=jaeger
    networks:
      monitoring:
        aliases:
          - demo-app
networks:
  monitoring:
