server:
  port: 8000
# endpoints are disabled by default
management:
  info:
    git:
      mode: full
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    httptrace:
      enabled: true
    env:
      enabled: true
# Disable lazy loading for this app
spring:
  jpa:
    open-in-view: false